# Beginner EDA Practice Exercises

## Data Problems and Solutions

This notebook contains simple practice exercises for:

1. Initial Data Inspection
2. Missing Values
3. Duplicate Rows
4. Wrong Data Types
5. Invalid Values
6. Inconsistent Categories
7. Outliers
8. Class Imbalance

> Skewed Data is not included in this notebook.

For every task:

1. Read the instructions.
2. Complete the `TODO` lines.
3. Run the cell.
4. Check the result.

## Learning Goal

By the end of this notebook, students should be able to detect and treat common data-quality problems using basic Pandas functions.

# 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully.")

Libraries imported successfully.

# 2. Create the Practice Dataset

The dataset below contains intentional problems.

Do not change `raw_df`. Create a copy for every task.

In [2]:
data = {
    "customer_id": [201, 202, 203, 204, 205, 205, 206, 207, 208, 209],
    "age": [22, 35, "unknown", 44, -5, -5, 39, 28, 135, 51],
    "city": [
        "Riyadh",
        "Jeddah",
        " riyadh ",
        "RIYADH",
        "Dammam",
        "Dammam",
        None,
        "JED",
        "Tabuk",
        "jeddah "
    ],
    "monthly_spend": [180, 320, 210, np.nan, 400, 400, 260, 195, 4200, 305],
    "satisfaction": [4, 5, 3, 4, 8, 8, np.nan, 2, 5, 4],
    "churn": ["No", "No", "Yes", "No", "No", "No", "No", "Yes", "No", "No"]
}

df = pd.DataFrame(data)

raw_df = df.copy()

display(raw_df)

   customer_id      age      city  monthly_spend  satisfaction churn
0          201       22    Riyadh          180.0           4.0    No
1          202       35    Jeddah          320.0           5.0    No
2          203  unknown   riyadh           210.0           3.0   Yes
3          204       44    RIYADH            NaN           4.0    No
4          205       -5    Dammam          400.0           8.0    No
5          205       -5    Dammam          400.0           8.0    No
6          206       39       NaN          260.0           NaN    No
7          207       28       JED          195.0           2.0   Yes
8          208      135     Tabuk         4200.0           5.0    No
9          209       51   jeddah           305.0           4.0    No

# Task 1: Initial Data Inspection

Complete the following:

1. Display the first five rows.
2. Print the dataset shape.
3. Display the column names.
4. Display the data types.
5. Count the missing values.

In [3]:
task_1 = raw_df.copy()

# TODO 1: Display the first five rows.
print(task_1.info())

# TODO 2: Print the shape.
print("------------------")
print(task_1.shape)

# TODO 3: Display the column names.
print("------------------")
print(task_1.columns)

# TODO 4: Display the data types.
print("------------------")
print(task_1.dtypes)

# TODO 5: Count missing values.
print("------------------")
print(task_1.isna().sum())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    10 non-null     int64
 1   age            10 non-null     object
 2   city           9 non-null      str
 3   monthly_spend  9 non-null      float64
 4   satisfaction   9 non-null      float64
 5   churn          10 non-null     str
dtypes: float64(2), int64(1), object(1), str(2)
memory usage: 612.0+ bytes
None
------------------
(10, 6)
------------------
Index(['customer_id', 'age', 'city', 'monthly_spend', 'satisfaction', 'churn'], dtype='str')
------------------
customer_id        int64
age               object
city                 str
monthly_spend    float64
satisfaction     float64
churn                str
dtype: object
------------------
customer_id      0
age              0
city             1
monthly_spend    1
satisfaction     1
churn            0
dtype: int64

## Check Your Understanding

Write your answers as comments:

- How many rows are there?
- Which column has the wrong data type?
- Which columns contain missing values?

In [4]:
# Number of rows:
# 10
# Column with wrong data type:
# age
# Columns with missing values:
# satisfaction - city - monthly_spend

# Task 2: Missing Values

Use a copy of `raw_df`.

Complete the following:

1. Count missing values.
2. Fill missing `monthly_spend` with the median.
3. Fill missing `city` with `"Unknown"`.
4. Fill missing `satisfaction` with the median.
5. Count missing values again.

In [5]:
task_2 = raw_df.copy()

# TODO 1: Count missing values.
print("missing values before")
print(task_2.isna().sum())

# TODO 2: Fill missing monthly_spend with the median.
task_2["monthly_spend"] = task_2["monthly_spend"].fillna(task_2["monthly_spend"].median())

# TODO 3: Fill missing city with "Unknown".
task_2["city"] = task_2["city"].fillna("Unknown")

# TODO 4: Fill missing satisfaction with the median.
task_2["satisfaction"] = task_2["satisfaction"].fillna(task_2["satisfaction"].median())

# TODO 5: Count missing values again.
print("missing values after")
print(task_2.isna().sum())

missing values before
customer_id      0
age              0
city             1
monthly_spend    1
satisfaction     1
churn            0
dtype: int64
missing values after
customer_id      0
age              0
city             0
monthly_spend    0
satisfaction     0
churn            0
dtype: int64

# Task 3: Duplicate Rows

Complete the following:

1. Count exact duplicate rows.
2. Display all copies of duplicated rows.
3. Remove exact duplicates.
4. Reset the index.
5. Print the shape before and after cleaning.

In [6]:
task_3 = raw_df.copy()

# TODO 1: Count duplicate rows.
print(task_3.duplicated().sum())

# TODO 2: Display duplicated rows.
print(task_3[task_3.duplicated()])

# Save the original shape before cleaning.
shape_before = task_3.shape

# TODO 3: Remove exact duplicates.
task_3 = task_3.drop_duplicates()

# TODO 4: Reset the index.
task_3 = task_3.reset_index(drop=True)

# TODO 5: Print the shape before and after.
print(shape_before)
print(task_3.shape)

1
   customer_id age    city  monthly_spend  satisfaction churn
5          205  -5  Dammam          400.0           8.0    No
(10, 6)
(9, 6)

# Task 4: Wrong Data Type

The `age` column contains the word `"unknown"`.

Complete the following:

1. Display the current `age` data type.
2. Convert `age` to numeric using `errors="coerce"`.
3. Display the new data type.
4. Count missing age values after conversion.

In [7]:
task_4 = raw_df.copy()

# TODO 1: Display the current age data type.


# TODO 2: Convert age to numeric.


# TODO 3: Display the new age data type.


# TODO 4: Count missing age values.

# Task 5: Invalid Values

Use these rules:

- Valid age: 0 to 100
- Valid satisfaction: 1 to 5

Complete the following:

1. Convert `age` to numeric.
2. Display invalid age rows.
3. Display invalid satisfaction rows.
4. Replace invalid values with `NaN`.
5. Fill missing age and satisfaction with their medians.
6. Verify the final ranges.

In [8]:
task_5 = raw_df.copy()

# TODO 1: Convert age to numeric.


# TODO 2: Display invalid ages.


# TODO 3: Display invalid satisfaction values.


# TODO 4A: Replace invalid ages with NaN.


# TODO 4B: Replace invalid satisfaction values with NaN.


# TODO 5A: Fill missing ages with the median.


# TODO 5B: Fill missing satisfaction with the median.


# TODO 6: Print the final age and satisfaction ranges.

# Task 6: Inconsistent Categories

Clean the `city` column in this order:

1. Fill missing values with `"Unknown"`.
2. Convert values to strings.
3. Remove extra spaces.
4. Convert text to lowercase.
5. Replace `"jed"` with `"jeddah"`.
6. Convert values to title case.
7. Display the final category counts.

In [9]:
task_6 = raw_df.copy()

# TODO: Clean the city column using method chaining.


# TODO: Display the final value counts.

# Task 7: Outliers

Use the IQR method on `monthly_spend`.

Complete the following:

1. Calculate Q1.
2. Calculate Q3.
3. Calculate IQR.
4. Calculate lower and upper limits.
5. Display possible outlier rows.
6. Create a new column called `monthly_spend_capped`.
7. Compare the original and capped values.

In [10]:
task_7 = raw_df.copy()

# TODO 1: Calculate Q1.


# TODO 2: Calculate Q3.


# TODO 3: Calculate IQR.


# TODO 4: Calculate lower and upper limits.


# TODO 5: Display possible outliers.


# TODO 6: Create monthly_spend_capped using clip().


# TODO 7: Compare original and capped values.

## Optional Visualization

Create a box plot for `monthly_spend`.

In [11]:
task_7_plot = raw_df.copy()

# TODO: Create a horizontal box plot for monthly_spend.

# Task 8: Class Imbalance

Use the `churn` column.

Complete the following:

1. Count each class.
2. Calculate the class percentages.
3. Display both in one DataFrame.
4. Draw a bar chart.
5. Check whether the percentages sum to 100.
6. Write whether the target is balanced or imbalanced.

In [12]:
task_8 = raw_df.copy()

# TODO 1: Count churn classes.


# TODO 2: Calculate percentages.


# TODO 3: Create a summary DataFrame.


# TODO 4: Draw a bar chart.


# TODO 5: Check that percentages sum to 100.


# Conclusion:

# Final Challenge: Clean the Complete Dataset

Create a DataFrame called `clean_df`.

Complete these steps:

1. Remove exact duplicate rows.
2. Convert `age` to numeric.
3. Replace invalid ages with `NaN`.
4. Replace invalid satisfaction values with `NaN`.
5. Fill missing age with the median.
6. Fill missing monthly spending with the median.
7. Fill missing satisfaction with the median.
8. Standardize city values.
9. Create a capped spending column using IQR.
10. Verify duplicates, missing values, valid ranges, and final categories.

In [13]:
clean_df = raw_df.copy()

# TODO 1: Remove exact duplicates.


# TODO 2: Convert age to numeric.


# TODO 3: Replace invalid ages with NaN.


# TODO 4: Replace invalid satisfaction with NaN.


# TODO 5: Fill missing age.


# TODO 6: Fill missing monthly_spend.


# TODO 7: Fill missing satisfaction.


# TODO 8: Standardize city values.


# TODO 9: Calculate IQR limits and create monthly_spend_capped.


# TODO 10: Verify the final dataset.


display(clean_df)

   customer_id      age      city  monthly_spend  satisfaction churn
0          201       22    Riyadh          180.0           4.0    No
1          202       35    Jeddah          320.0           5.0    No
2          203  unknown   riyadh           210.0           3.0   Yes
3          204       44    RIYADH            NaN           4.0    No
4          205       -5    Dammam          400.0           8.0    No
5          205       -5    Dammam          400.0           8.0    No
6          206       39       NaN          260.0           NaN    No
7          207       28       JED          195.0           2.0   Yes
8          208      135     Tabuk         4200.0           5.0    No
9          209       51   jeddah           305.0           4.0    No

# Reflection Questions

Answer in your own words:

1. What is the difference between a missing value and an invalid value?
2. Why should a duplicated ID not always be deleted?
3. Why is the median useful when outliers exist?
4. Why should an outlier be investigated before deletion?
5. Why can accuracy be misleading when the target classes are imbalanced?

In [14]:
# 1.

# 2.

# 3.

# 4.

# 5.

# Submission Checklist

- [ ] All code cells run without errors.
- [ ] A separate copy was used for every task.
- [ ] Missing values were treated.
- [ ] Exact duplicates were removed.
- [ ] Data types were corrected.
- [ ] Invalid values were treated.
- [ ] Categories were standardized.
- [ ] Outliers were detected and capped.
- [ ] Class balance was checked.
- [ ] The final challenge was completed.