# Exploratory Data Analysis (EDA)
## Detailed Student Workbook

Exploratory Data Analysis is a structured process for understanding data before cleaning, feature engineering, statistical analysis, or modeling.

The goal is not merely to create charts. A complete EDA should answer:

- Is the dataset valid enough for analysis?
- Which issues require cleaning?
- Which variables appear important?
- Are there clear relationships?
- Are any values impossible or suspicious?
- Is the target balanced?
- Which transformations are required before modeling?

## Topics

1. EDA workflow and analytical questions
2. Loading data
3. Displaying samples
4. Rows, columns, names, and data types
5. Missing values
6. Duplicate rows and duplicate identifiers
7. Descriptive statistics
8. Numerical and categorical distributions
9. Outlier detection
10. Relationships and correlations
11. Class-balance analysis
12. Domain-validity checks
13. Transformations before modeling
14. Findings documentation
15. Final guided EDA project

## Dataset Scenario

A subscription company wants to understand customer churn.

Each row represents one customer.

| Column | Meaning |
|---|---|
| `customer_id` | Unique customer identifier |
| `age` | Customer age |
| `gender` | Customer gender |
| `city` | Customer city |
| `tenure_months` | Number of months with the company |
| `monthly_spend` | Average monthly spending |
| `support_calls` | Number of support calls |
| `satisfaction_score` | Satisfaction score from 1 to 5 |
| `contract_type` | Monthly, quarterly, or annual contract |
| `payment_method` | Customer payment method |
| `is_premium` | Premium membership indicator |
| `purchases_last_6m` | Purchases in the last six months |
| `signup_date` | Signup date |
| `churn` | Target variable: Yes or No |

The dataset intentionally contains missing values, duplicates, unreasonable values, outliers, and class imbalance.

## EDA as a Decision Process

```text
Understand the business question
        ↓
Load and inspect the data
        ↓
Assess quality and validity
        ↓
Analyze each variable
        ↓
Study relationships
        ↓
Inspect the target
        ↓
Identify transformations
        ↓
Document findings and recommendations
```

Each output should support an analytical conclusion.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 100)
pd.set_option("display.float_format", lambda value: f"{value:,.2f}")

print("EDA environment is ready.")

EDA environment is ready.

# 1. Loading Data

## CSV

```python
df = pd.read_csv("file.csv")
```

## Excel

```python
df = pd.read_excel("file.xlsx")
```

## URL

```python
df = pd.read_csv("https://example.com/data.csv")
```

## Google Colab Upload

```python
from google.colab import files

uploaded = files.upload()
file_name = next(iter(uploaded))
df = pd.read_csv(file_name)
```

After loading, verify that the DataFrame exists, is not empty, and contains the expected columns.

In [2]:
# Upload the provided file to Google Colab first.
#
# from google.colab import files
# uploaded = files.upload()
# file_name = next(iter(uploaded))
# df = pd.read_csv(file_name)

data_path = Path("eda_customer_churn_dataset.csv")

# TODO: Load the provided CSV file into a DataFrame named df.
df = pd.read_csv(data_path)

### Exercise 1: Load the Dataset

**Level:** Foundation  
**Learning objective:** Load a CSV file into pandas.

#### Task
Upload the provided CSV file and store it in `df`.

#### Expected result
```text
Expected shape: (328, 14)
```

<details>
<summary><strong>Hint</strong></summary>

Use `pd.read_csv()`.

</details>

In [3]:
# TODO: Load the dataset.

# TODO: Print df.shape.
df.shape

(328, 14)

### Exercise 2: Safe CSV Loader

**Level:** Applied  
**Learning objective:** Create a reusable data-loading function.

#### Task
Write `load_csv(path)` that checks whether the file exists and rejects an empty DataFrame.

#### Expected result
```text
Return a non-empty DataFrame.
```

<details>
<summary><strong>Hint</strong></summary>

Use `Path.exists()` and `DataFrame.empty`.

</details>

In [4]:
def load_csv(path: str | Path) -> pd.DataFrame:
    # TODO
    path = Path(path)

    if not Path.exists():
        raise ValueError("File does not exist")

    data = pd.read_csv(path)

    if data.empty:
        raise ValueError("Data frame is empty")
    return data

# 2. Initial Inspection

Initial inspection answers:

- What does one row represent?
- How many observations and variables exist?
- What columns are available?
- Which variables are numerical or categorical?
- Are the data types appropriate?
- Do random rows look reasonable?

## Useful Methods

| Method | Purpose |
|---|---|
| `head()` | First rows |
| `tail()` | Last rows |
| `sample()` | Random rows |
| `shape` | Rows and columns |
| `columns` | Column names |
| `dtypes` | Data types |
| `info()` | Non-null counts and types |
| `nunique()` | Number of distinct values |

## Data Types

| pandas type | Typical meaning |
|---|---|
| `int64` | Integer |
| `float64` | Decimal number |
| `object` | Text or mixed values |
| `bool` | True/False |
| `datetime64[ns]` | Date/time |
| `category` | Categorical variable |

Dates loaded from CSV usually begin as `object` and should be converted explicitly.

### Exercise 3: Display Samples

**Level:** Foundation  
**Learning objective:** Inspect different areas of the dataset.

#### Task
Display the first five rows, last three rows, and a reproducible sample of five rows.

#### Expected result
```text
Three DataFrame outputs.
```

<details>
<summary><strong>Hint</strong></summary>

Use `head()`, `tail()`, and `sample(random_state=42)`.

</details>

In [5]:
# TODO: Display the three samples.
df.head()

,customer_id,age,gender,city,tenure_months,monthly_spend,support_calls,satisfaction_score,contract_type,payment_method,is_premium,purchases_last_6m,signup_date,churn
0,CUST-0001,39.00,Male,Dammam,28.00,123.92,2.00,3.40,Monthly,Digital Wallet,False,7.00,2023-09-20,No
1,CUST-0002,25.00,Male,Riyadh,9.00,97.33,2.00,3.08,Annual,Cash,False,2.00,2020-04-19,No
2,CUST-0003,44.00,Female,Madinah,12.00,86.78,1.00,4.13,Annual,Bank Transfer,False,4.00,2024-02-08,No
3,CUST-0004,46.00,Male,Riyadh,67.00,104.40,2.00,3.70,Monthly,Credit Card,False,8.00,2024-04-08,No
4,CUST-0005,18.00,Female,Madinah,1.00,97.94,6.00,NaN,Monthly,Credit Card,False,5.00,2021-04-20,Yes

In [6]:
df.tail()

,customer_id,age,gender,city,tenure_months,monthly_spend,support_calls,satisfaction_score,contract_type,payment_method,is_premium,purchases_last_6m,signup_date,churn
323,CUST-0104,44.00,Female,Riyadh,39.00,117.36,1.00,4.09,Monthly,Digital Wallet,False,8.00,2021-11-18,No
324,CUST-0156,55.00,Female,Riyadh,18.00,83.61,4.00,2.77,Monthly,Credit Card,False,4.00,2021-08-28,No
325,CUST-0212,21.00,Male,Jeddah,36.00,203.23,1.00,4.34,Quarterly,Credit Card,True,10.00,2022-06-24,No
326,CUST-0279,49.00,Male,Riyadh,2.00,NaN,1.00,3.18,Annual,Cash,False,0.00,2021-04-05,No
327,CUST-0302,19.00,Female,Riyadh,60.00,111.79,4.00,2.59,Monthly,Digital Wallet,False,11.00,2021-05-24,No

In [7]:
df.sample(random_state=42)

,customer_id,age,gender,city,tenure_months,monthly_spend,support_calls,satisfaction_score,contract_type,payment_method,is_premium,purchases_last_6m,signup_date,churn
231,CUST-0232,30.00,Male,Jeddah,55.00,196.52,6.00,2.10,Monthly,Credit Card,False,6.00,2024-02-29,No

### Exercise 4: Dataset Dimensions

    **Level:** Foundation  
    **Learning objective:** Interpret `DataFrame.shape`.

    #### Task
    Print rows and columns separately.

    #### Expected result
    ```text
    Rows: 328
Columns: 14
    ```

    <details>
    <summary><strong>Hint</strong></summary>

    Unpack `df.shape`.

    </details>

In [8]:
# TODO: Print rows and columns.
rows, columns = df.shape
print(f"Rows: {rows}")
print(f"Columns: {columns}")

Rows: 328
Columns: 14

### Exercise 5: Column-Type Classification

    **Level:** Applied  
    **Learning objective:** Separate numerical and non-numerical variables.

    #### Task
    Create lists named `numeric_columns` and `other_columns`.

    #### Expected result
    ```text
    Numeric columns: 6
Other columns: 8
    ```

    <details>
    <summary><strong>Hint</strong></summary>

    Use `select_dtypes()`.

    </details>

In [9]:
# TODO: Create both column lists.
numeric_columns = []
other_columns = []

# TODO: Print their names and lengths.
for column in df.select_dtypes(include='number'):
    numeric_columns.append(column)

for column in df.select_dtypes(exclude='number'):
    other_columns.append(column)

print(f"Numeric columns: {len(numeric_columns)}")
print(f"Other columns: {len(other_columns)}")

Numeric columns: 6
Other columns: 8

### Exercise 6: Convert Signup Date

**Level:** Applied  
**Learning objective:** Convert a text column to datetime.

#### Task
Convert `signup_date` using `errors='coerce'`.

#### Expected result
```text
datetime64[ns]
```

<details>
<summary><strong>Hint</strong></summary>

Use `pd.to_datetime()`.

</details>

In [10]:
# TODO: Convert signup_date.
df["signup_date"] = pd.to_datetime(df["signup_date"], errors='coerce')

# TODO: Print the resulting dtype.
print(df["signup_date"])

0     2023-09-20
1     2020-04-19
2     2024-02-08
3     2024-04-08
4     2021-04-20
         ...
323   2021-11-18
324   2021-08-28
325   2022-06-24
326   2021-04-05
327   2021-05-24
Name: signup_date, Length: 328, dtype: datetime64[us]

### Exercise 7: Column Audit Table

**Level:** Challenge  
**Learning objective:** Create a reusable metadata summary.

#### Task
Build a table with column, dtype, non-null count, missing count, unique count, and example value.

#### Expected result
```text
One row per column.
```

<details>
<summary><strong>Hint</strong></summary>

Loop through `df.columns` or combine pandas Series.

</details>

In [11]:
# TODO: Build column_audit.
filtered_columns_table = []

for column in df.columns:
    row = {
        "Column": column,
        "dtype": df[column].dtype,
        "non-null count": df[column].notna().sum(),
        "missing count": df[column].isnull().sum(),
        "unique count": df[column].nunique(),
        "example value": df[column].dropna().iloc[0]
    }

    filtered_columns_table.append(row)
    filtered_df = pd.DataFrame(filtered_columns_table)
    # TODO: Display it.
    print(filtered_df)

        Column dtype  non-null count  missing count  unique count  \
0  customer_id   str             328              0           320

  example value
0     CUST-0001
        Column    dtype  non-null count  missing count  unique count  \
0  customer_id      str             328              0           320
1          age  float64             328              0            47

  example value
0     CUST-0001
1         39.00
        Column    dtype  non-null count  missing count  unique count  \
0  customer_id      str             328              0           320
1          age  float64             328              0            47
2       gender      str             319              9             2

  example value
0     CUST-0001
1         39.00
2          Male
        Column    dtype  non-null count  missing count  unique count  \
0  customer_id      str             328              0           320
1          age  float64             328              0            47
2       gender      str             319              9             2
3         city      str             318             10             5

  example value
0     CUST-0001
1         39.00
2          Male
3        Dammam
          Column    dtype  non-null count  missing count  unique count  \
0    customer_id      str             328              0           320
1            age  float64             328              0            47
2         gender      str             319              9             2
3           city      str             318             10             5
4  tenure_months  float64             328              0            72

  example value
0     CUST-0001
1         39.00
2          Male
3        Dammam
4         28.00
          Column    dtype  non-null count  missing count  unique count  \
0    customer_id      str             328              0           320
1            age  float64             328              0            47
2         gender      str             319              9             2
3           city      str             318             10             5
4  tenure_months  float64             328              0            72
5  monthly_spend  float64             320              8           311

  example value
0     CUST-0001
1         39.00
2          Male
3        Dammam
4         28.00
5        123.92
          Column    dtype  non-null count  missing count  unique count  \
0    customer_id      str             328              0           320
1            age  float64             328              0            47
2         gender      str             319              9             2
3           city      str             318             10             5
4  tenure_months  float64             328              0            72
5  monthly_spend  float64             320              8           311
6  support_calls  float64             328              0            10

  example value
0     CUST-0001
1         39.00
2          Male
3        Dammam
4         28.00
5        123.92
6          2.00
               Column    dtype  non-null count  missing count  unique count  \
0         customer_id      str             328              0           320
1                 age  float64             328              0            47
2              gender      str             319              9             2
3                city      str             318             10             5
4       tenure_months  float64             328              0            72
5       monthly_spend  float64             320              8           311
6       support_calls  float64             328              0            10
7  satisfaction_score  float64             316             12           172

  example value
0     CUST-0001
1         39.00
2          Male
3        Dammam
4         28.00
5        123.92
6          2.00
7          3.40
               Column    dtype  non-null count  missing count  unique count  \
0         customer_id      str             328              0           320
1                 age  float64             328              0            47
2              gender      str             319              9             2
3                city      str             318             10             5
4       tenure_months  float64             328              0            72
5       monthly_spend  float64             320              8           311
6       support_calls  float64             328              0            10
7  satisfaction_score  float64             316             12           172
8       contract_type      str             328              0             3

  example value
0     CUST-0001
1         39.00
2          Male
3        Dammam
4         28.00
5        123.92
6          2.00
7          3.40
8       Monthly
               Column    dtype  non-null count  missing count  unique count  \
0         customer_id      str             328              0           320
1                 age  float64             328              0            47
2              gender      str             319              9             2
3                city      str             318             10             5
4       tenure_months  float64             328              0            72
5       monthly_spend  float64             320              8           311
6       support_calls  float64             328              0            10
7  satisfaction_score  float64             316             12           172
8       contract_type      str             328              0             3
9      payment_method      str             323              5             4

    example value
0       CUST-0001
1           39.00
2            Male
3          Dammam
4           28.00
5          123.92
6            2.00
7            3.40
8         Monthly
9  Digital Wallet
                Column    dtype  non-null count  missing count  unique count  \
0          customer_id      str             328              0           320
1                  age  float64             328              0            47
2               gender      str             319              9             2
3                 city      str             318             10             5
4        tenure_months  float64             328              0            72
5        monthly_spend  float64             320              8           311
6        support_calls  float64             328              0            10
7   satisfaction_score  float64             316             12           172
8        contract_type      str             328              0             3
9       payment_method      str             323              5             4
10          is_premium     bool             328              0             2

     example value
0        CUST-0001
1            39.00
2             Male
3           Dammam
4            28.00
5           123.92
6             2.00
7             3.40
8          Monthly
9   Digital Wallet
10           False
                Column    dtype  non-null count  missing count  unique count  \
0          customer_id      str             328              0           320
1                  age  float64             328              0            47
2               gender      str             319              9             2
3                 city      str             318             10             5
4        tenure_months  float64             328              0            72
5        monthly_spend  float64             320              8           311
6        support_calls  float64             328              0            10
7   satisfaction_score  float64             316             12           172
8        contract_type      str             328              0             3
9       payment_method      str             323              5             4
10          is_premium     bool             328              0             2
11   purchases_last_6m  float64             328              0            19

     example value
0        CUST-0001
1            39.00
2             Male
3           Dammam
4            28.00
5           123.92
6             2.00
7             3.40
8          Monthly
9   Digital Wallet
10           False
11            7.00
                Column           dtype  non-null count  missing count  \
0          customer_id             str             328              0
1                  age         float64             328              0
2               gender             str             319              9
3                 city             str             318             10
4        tenure_months         float64             328              0
5        monthly_spend         float64             320              8
6        support_calls         float64             328              0
7   satisfaction_score         float64             316             12
8        contract_type             str             328              0
9       payment_method             str             323              5
10          is_premium            bool             328              0
11   purchases_last_6m         float64             328              0
12         signup_date  datetime64[us]             328              0

    unique count        example value
0            320            CUST-0001
1             47                39.00
2              2                 Male
3              5               Dammam
4             72                28.00
5            311               123.92
6             10                 2.00
7            172                 3.40
8              3              Monthly
9              4       Digital Wallet
10             2                False
11            19                 7.00
12           293  2023-09-20 00:00:00
                Column           dtype  non-null count  missing count  \
0          customer_id             str             328              0
1                  age         float64             328              0
2               gender             str             319              9
3                 city             str             318             10
4        tenure_months         float64             328              0
5        monthly_spend         float64             320              8
6        support_calls         float64             328              0
7   satisfaction_score         float64             316             12
8        contract_type             str             328              0
9       payment_method             str             323              5
10          is_premium            bool             328              0
11   purchases_last_6m         float64             328              0
12         signup_date  datetime64[us]             328              0
13               churn             str             328              0

    unique count        example value
0            320            CUST-0001
1             47                39.00
2              2                 Male
3              5               Dammam
4             72                28.00
5            311               123.92
6             10                 2.00
7            172                 3.40
8              3              Monthly
9              4       Digital Wallet
10             2                False
11            19                 7.00
12           293  2023-09-20 00:00:00
13             2                   No

# 3. Missing-Value Analysis

Missing values may be represented by:

- `NaN`,
- `None`,
- empty strings,
- placeholders such as `Unknown`, `N/A`, or `-999`.

## Counts

```python
df.isna().sum()
```

## Percentages

```python
df.isna().mean() * 100
```

## Decision Questions

- How much is missing?
- Which variables are affected?
- Is missingness related to a group or target?
- Is the variable important?
- Can it be imputed?
- Would dropping rows introduce bias?

## Possible Treatments

| Situation | Possible action |
|---|---|
| Small amount in non-critical rows | Drop affected rows |
| Numerical variable | Median or model-based imputation |
| Categorical variable | Mode or `Unknown` |
| Missingness carries information | Add a missing indicator |
| Very high missingness | Consider dropping the variable |
| Ordered time data | Forward/backward fill only when justified |

No treatment should be automatic.

### Exercise 8: Missing Counts

**Level:** Foundation  
**Learning objective:** Count missing values.

#### Task
Print missing counts sorted descending.

#### Expected result
```text
Columns with missing values should appear first.
```

<details>
<summary><strong>Hint</strong></summary>

Use `isna().sum().sort_values()`.

</details>

In [12]:
# TODO: Calculate missing counts.
df[df.columns].isna().sum().sort_values(ascending=False)

satisfaction_score    12
city                  10
gender                 9
monthly_spend          8
payment_method         5
customer_id            0
tenure_months          0
age                    0
support_calls          0
contract_type          0
is_premium             0
purchases_last_6m      0
signup_date            0
churn                  0
dtype: int64

### Exercise 9: Missing Percentage Summary

**Level:** Applied  
**Learning objective:** Quantify missingness.

#### Task
Create a table with count and percentage, excluding columns with zero missing values.

#### Expected result
```text
One row per affected column.
```

<details>
<summary><strong>Hint</strong></summary>

Filter where missing count is greater than zero.

</details>

In [13]:
# TODO: Build and display missing_summary.
#null_columns_table = []
for column in df.columns:
    if df[column].isna().sum() > 0:
        print(f"Column: {column} has: {df[column].isna().sum()} null count")
        print(f"Column: {column} has: {df[column].isna().mean() * 100 :.2f} null mean")
        print()

Column: gender has: 9 null count
Column: gender has: 2.74 null mean

Column: city has: 10 null count
Column: city has: 3.05 null mean

Column: monthly_spend has: 8 null count
Column: monthly_spend has: 2.44 null mean

Column: satisfaction_score has: 12 null count
Column: satisfaction_score has: 3.66 null mean

Column: payment_method has: 5 null count
Column: payment_method has: 1.52 null mean

### Exercise 10: Missingness by Target

**Level:** Challenge  
**Learning objective:** Investigate whether missingness differs across churn classes.

#### Task
Compare the missing rate of satisfaction score between churn classes.

#### Expected result
```text
A grouped missing-rate table.
```

<details>
<summary><strong>Hint</strong></summary>

Create a Boolean indicator then group by `churn`.

</details>

In [14]:
# TODO: Compare missing satisfaction by churn.
df["missing satisfaction score"] = df["satisfaction_score"].isna()

missing_rate_by_churn = df.groupby("churn")["missing satisfaction score"].mean() * 100
print(missing_rate_by_churn)

churn
No    3.40
Yes   5.88
Name: missing satisfaction score, dtype: float64

### Exercise 11: Missing-Value Decision Table

**Level:** Challenge  
**Learning objective:** Turn analysis into recommendations.

#### Task
Document variable, missing percentage, proposed action, and justification for each affected column.

#### Expected result
```text
One recommendation per affected variable.
```

<details>
<summary><strong>Hint</strong></summary>

Use both quantity and business meaning.

</details>

In [15]:
# TODO: Build missing_decisions.

recommendations = {
    "gender": {
        "action": "fill using mode",
        "justification": "low missing rate"
    },

    "city": {
        "action": "fill using mode",
        "justification": "low missing rate"
    },

    "monthly_spend" : {
        "action": "fill using mean",
        "justification": "low missing rate"
    },

    "satisfaction_score": {
        "action": "fill using mean",
        "justification": "low missing rate"
    },

    "payment_method": {
        "action": "fill using mean",
        "justification": "low missing rate"
    }
}

missing_decision_rows = []

for column, details in recommendations.items():
    missing_percentage = df[column].isna().mean() * 100

    row = {
        "column": column,
        "missing percentage": missing_percentage,
        "proposed action": details["action"],
        "justification": details["justification"]
    }
    missing_decision_rows.append(row)

missing_decisions = pd.DataFrame(missing_decision_rows)
missing_decisions

               column  missing percentage  proposed action     justification
0              gender                2.74  fill using mode  low missing rate
1                city                3.05  fill using mode  low missing rate
2       monthly_spend                2.44  fill using mean  low missing rate
3  satisfaction_score                3.66  fill using mean  low missing rate
4      payment_method                1.52  fill using mean  low missing rate

# 4. Duplicate Analysis

Duplicates may inflate counts, bias averages, distort target balance, or create leakage.

## Exact Duplicates

```python
df.duplicated().sum()
```

## All Rows in Duplicate Groups

```python
df[df.duplicated(keep=False)]
```

## Duplicate Identifiers

```python
df["customer_id"].duplicated().sum()
```

Always distinguish exact duplicates from legitimate repeated events.

### Exercise 12: Count Exact Duplicates

**Level:** Foundation  
**Learning objective:** Detect exact repeated rows.

#### Task
Print the number of duplicate rows.

#### Expected result
```text
Duplicate rows: 8
```

<details>
<summary><strong>Hint</strong></summary>

Use `duplicated().sum()`.

</details>

In [16]:
# TODO: Count and print duplicate rows.
count = df["customer_id"].duplicated().sum()

print(f"Duplicate rows: {count}")

Duplicate rows: 8

### Exercise 13: Inspect Duplicate Groups

**Level:** Applied  
**Learning objective:** Display all rows belonging to duplicate groups.

#### Task
Display both original and repeated copies.

#### Expected result
```text
Both copies should be visible.
```

<details>
<summary><strong>Hint</strong></summary>

Use `keep=False`.

</details>

In [17]:
# TODO: Display duplicate groups.

print(df[df.duplicated(keep=False)])

    customer_id   age  gender    city  tenure_months  monthly_spend  \
12    CUST-0013 37.00    Male  Riyadh          39.00         176.80
27    CUST-0028 40.00     NaN  Jeddah          67.00         134.55
64    CUST-0065 44.00    Male  Jeddah          57.00         231.37
103   CUST-0104 44.00  Female  Riyadh          39.00         117.36
155   CUST-0156 55.00  Female  Riyadh          18.00          83.61
211   CUST-0212 21.00    Male  Jeddah          36.00         203.23
278   CUST-0279 49.00    Male  Riyadh           2.00            NaN
301   CUST-0302 19.00  Female  Riyadh          60.00         111.79
320   CUST-0013 37.00    Male  Riyadh          39.00         176.80
321   CUST-0028 40.00     NaN  Jeddah          67.00         134.55
322   CUST-0065 44.00    Male  Jeddah          57.00         231.37
323   CUST-0104 44.00  Female  Riyadh          39.00         117.36
324   CUST-0156 55.00  Female  Riyadh          18.00          83.61
325   CUST-0212 21.00    Male  Jeddah          36.00         203.23
326   CUST-0279 49.00    Male  Riyadh           2.00            NaN
327   CUST-0302 19.00  Female  Riyadh          60.00         111.79

     support_calls  satisfaction_score contract_type  payment_method  \
12            0.00                4.38       Monthly  Digital Wallet
27            1.00                3.97        Annual   Bank Transfer
64            1.00                3.95       Monthly     Credit Card
103           1.00                4.09       Monthly  Digital Wallet
155           4.00                2.77       Monthly     Credit Card
211           1.00                4.34     Quarterly     Credit Card
278           1.00                3.18        Annual            Cash
301           4.00                2.59       Monthly  Digital Wallet
320           0.00                4.38       Monthly  Digital Wallet
321           1.00                3.97        Annual   Bank Transfer
322           1.00                3.95       Monthly     Credit Card
323           1.00                4.09       Monthly  Digital Wallet
324           4.00                2.77       Monthly     Credit Card
325           1.00                4.34     Quarterly     Credit Card
326           1.00                3.18        Annual            Cash
327           4.00                2.59       Monthly  Digital Wallet

     is_premium  purchases_last_6m signup_date churn  \
12         True              14.00  2025-05-24    No
27        False              11.00  2023-05-28    No
64         True              11.00  2023-11-19   Yes
103       False               8.00  2021-11-18    No
155       False               4.00  2021-08-28    No
211        True              10.00  2022-06-24    No
278       False               0.00  2021-04-05    No
301       False              11.00  2021-05-24    No
320        True              14.00  2025-05-24    No
321       False              11.00  2023-05-28    No
322        True              11.00  2023-11-19   Yes
323       False               8.00  2021-11-18    No
324       False               4.00  2021-08-28    No
325        True              10.00  2022-06-24    No
326       False               0.00  2021-04-05    No
327       False              11.00  2021-05-24    No

     missing satisfaction score
12                        False
27                        False
64                        False
103                       False
155                       False
211                       False
278                       False
301                       False
320                       False
321                       False
322                       False
323                       False
324                       False
325                       False
326                       False
327                       False

### Exercise 14: Identifier Uniqueness

**Level:** Applied  
**Learning objective:** Check whether a key is truly unique.

#### Task
Count repeated customer IDs and display the affected records.

#### Expected result
```text
Repeated IDs should be identified.
```

<details>
<summary><strong>Hint</strong></summary>

Use `duplicated(keep=False)` on `customer_id`.

</details>

In [18]:
# TODO: Inspect duplicated customer IDs.
print(df["customer_id"].duplicated(keep=False).sum())

16

### Exercise 15: Deduplicated Copy

    **Level:** Applied  
    **Learning objective:** Remove duplicates without modifying raw data.

    #### Task
    Create `df_deduplicated` and compare row counts.

    #### Expected result
    ```text
    Original: 328
After deduplication: 320
    ```

    <details>
    <summary><strong>Hint</strong></summary>

    Use `.drop_duplicates().copy()`.

    </details>

In [19]:
# TODO: Create df_deduplicated.
df_deduplicated = df.drop_duplicates()
df.reset_index([0])

# TODO: Print before and after counts.
row_original, column = df.shape
row_new, column = df_deduplicated.shape

print(row_original)
print(row_new)

328
320

# 5. Descriptive Statistics

## Numerical Summary

```python
df.describe()
```

| Measure | Meaning |
|---|---|
| count | Non-missing observations |
| mean | Arithmetic average |
| std | Standard deviation |
| min/max | Observed extremes |
| 25%, 50%, 75% | Quartiles |

## Categorical Summary

```python
df.describe(include="object")
```

This reports count, unique categories, most frequent category, and its frequency.

A large difference between mean and median may indicate skewness or outliers.

### Exercise 16: Numerical Summary

**Level:** Foundation  
**Learning objective:** Inspect numerical distributions.

#### Task
Display descriptive statistics for numerical columns.

#### Expected result
```text
Numerical summary table.
```

<details>
<summary><strong>Hint</strong></summary>

Use `describe()`.

</details>

In [20]:
# TODO: Display numerical statistics.
df.describe()

,age,tenure_months,monthly_spend,support_calls,satisfaction_score,purchases_last_6m,signup_date
count,328.00,328.00,320.00,328.00,316.00,328.00,328
mean,36.20,38.50,146.36,2.34,3.72,8.00,2022-11-11 06:35:07.317073
min,-4.00,1.00,-25.00,0.00,1.70,0.00,2020-01-04 00:00:00
25%,29.00,21.00,100.28,1.00,3.22,5.00,2021-05-28 12:00:00
50%,35.50,39.00,134.55,2.00,3.79,8.00,2022-11-18 12:00:00
75%,42.00,55.00,175.86,3.00,4.20,10.00,2024-04-09 18:00:00
max,145.00,160.00,"1,600.00",35.00,8.50,95.00,2025-09-29 00:00:00
std,11.94,21.42,116.70,2.63,0.77,5.91,NaN

### Exercise 17: Categorical Summary

**Level:** Foundation  
**Learning objective:** Inspect categorical distributions.

#### Task
Display descriptive statistics for object columns.

#### Expected result
```text
Categorical summary table.
```

<details>
<summary><strong>Hint</strong></summary>

Use `describe(include='object')`.

</details>

In [21]:
# TODO: Display categorical statistics.
df.describe(include="object")

C:\Users\khali\AppData\Local\Temp\ipykernel_11272\439498221.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

       customer_id gender    city contract_type payment_method churn
count          328    319     318           328            323   328
unique         320      2       5             3              4     2
top      CUST-0013   Male  Riyadh       Monthly    Credit Card    No
freq             2    167     127           175            105   294

### Exercise 18: Mean-Median Difference

**Level:** Applied  
**Learning objective:** Detect possible skewness.

#### Task
Build a table with mean, median, and absolute difference for numerical columns.

#### Expected result
```text
One row per numerical column.
```

<details>
<summary><strong>Hint</strong></summary>

Use `.mean()` and `.median()`.

</details>

In [25]:
# TODO: Build mean_median_comparison.
means = []
medians = []
differences = []

for column in numeric_columns:
    column_mean = df[column].mean()
    column_median = df[column].median()

    means.append(column_mean)
    medians.append(column_median)
    differences.append(abs(column_mean - column_median))

comparison = pd.DataFrame({
    "column": columns,
    "mean": means,
    "median": medians,
    "differences": differences
})

# TODO: Sort descending by difference.
print(comparison.sort_values("differences", ascending=False))

   column   mean  median  differences
2      14 146.36  134.55        11.81
0      14  36.20   35.50         0.70
1      14  38.50   39.00         0.50
3      14   2.34    2.00         0.34
4      14   3.72    3.79         0.07
5      14   8.00    8.00         0.00

### Exercise 19: Grouped Target Statistics

**Level:** Applied  
**Learning objective:** Compare feature behavior by churn.

#### Task
Compare count, mean, median, and standard deviation for selected variables by churn.

#### Expected result
```text
One grouped table.
```

<details>
<summary><strong>Hint</strong></summary>

Use `groupby().agg()`.

</details>

In [29]:
# TODO: Compare tenure, spend, calls, satisfaction, and purchases by churn.
sums = []
means = []
medians = []
stds = []

rows = []
selected_columns = [
    "tenure_months",
    "monthly_spend",
    "support_calls",
    "satisfaction_score",
    "purchases_last_6m"
]


for column in selected_columns:

    grouped = df.groupby("churn")[column].agg(["count", "mean", "median", "std"])
    no_mean = grouped.loc["No", "mean"]
    yes_mean = grouped.loc["Yes", "mean"]
    difference = abs(no_mean - yes_mean)

    rows.append({
        "column": column,
        "no_count": grouped.loc["No", "count"],
        "no_mean": no_mean,
        "no_median": grouped.loc["No", "median"],
        "no_std": grouped.loc["No", "std"],
        "yes_count": grouped.loc["Yes", "count"],
        "yes_mean": yes_mean,
        "yes_median": grouped.loc["Yes", "median"],
        "yes_std": grouped.loc["Yes", "std"],
        "difference": difference,
    })

comparison = pd.DataFrame(rows)

# TODO: Sort descending by difference.
print(comparison.sort_values("difference", ascending=False))

               column  no_count  no_mean  no_median  no_std  yes_count  \
1       monthly_spend       287   142.23     134.55   85.90         33
0       tenure_months       294    38.75      39.00   20.27         34
2       support_calls       294     2.18       2.00    1.90         34
3  satisfaction_score       284     3.74       3.84    0.75         32
4   purchases_last_6m       294     8.03       8.00    6.15         34

   yes_mean  yes_median  yes_std  difference
1    182.21      139.88   261.43       39.98
0     36.32       33.00    29.86        2.42
2      3.71        2.00     5.84        1.53
3      3.47        3.53     0.83        0.28
4      7.79        7.00     3.17        0.23

### Exercise 20: Suspicious Range Report

**Level:** Challenge  
**Learning objective:** Use statistics to identify unreasonable values.

#### Task
Create a table containing variable, observed minimum, observed maximum, expected range, and note.

#### Expected result
```text
At least six numerical variables.
```

<details>
<summary><strong>Hint</strong></summary>

Compare observed values with domain expectations.

</details>

In [ ]:
# TODO: Build suspicious_range_report.

# 6. Univariate Analysis

Univariate analysis examines one variable at a time.

## Numerical Variables

- histogram,
- boxplot,
- quantiles,
- skewness,
- central tendency,
- spread.

## Categorical Variables

- counts,
- percentages,
- cardinality,
- bar chart.

Before plotting, define the question the chart should answer.

## Histogram Example

```python
figure, axis = plt.subplots()
axis.hist(df["monthly_spend"].dropna(), bins=20)
axis.set_title("Monthly Spend Distribution")
axis.set_xlabel("Monthly Spend")
axis.set_ylabel("Frequency")
plt.show()
```

Interpret shape, peaks, skewness, gaps, and extremes.

## Boxplot Example

```python
figure, axis = plt.subplots()
axis.boxplot(df["support_calls"].dropna(), vert=False)
axis.set_title("Support Calls")
axis.set_xlabel("Calls")
plt.show()
```

A boxplot highlights median, interquartile range, and potential outliers.

### Exercise 21: Monthly-Spend Profile

**Level:** Foundation  
**Learning objective:** Summarize one numerical variable.

#### Task
Calculate count, mean, median, standard deviation, skewness, minimum, and maximum.

#### Expected result
```text
One Series or one-row DataFrame.
```

<details>
<summary><strong>Hint</strong></summary>

Use `.agg()` and `.skew()`.

</details>

In [ ]:
# TODO: Build monthly_spend_profile.

### Exercise 22: Monthly-Spend Histogram

**Level:** Foundation  
**Learning objective:** Visualize a numerical distribution.

#### Task
Create one histogram with title and axis labels.

#### Expected result
```text
One histogram.
```

<details>
<summary><strong>Hint</strong></summary>

Drop missing values before plotting.

</details>

In [ ]:
# TODO: Plot the histogram.

### Exercise 23: Support-Calls Boxplot

**Level:** Foundation  
**Learning objective:** Visualize spread and potential outliers.

#### Task
Create a horizontal boxplot.

#### Expected result
```text
One boxplot.
```

<details>
<summary><strong>Hint</strong></summary>

Use `axis.boxplot()`.

</details>

In [ ]:
# TODO: Plot the boxplot.

### Exercise 24: Contract-Type Frequency

**Level:** Applied  
**Learning objective:** Analyze a categorical variable.

#### Task
Create count and percentage tables and one bar chart.

#### Expected result
```text
Two tables and one chart.
```

<details>
<summary><strong>Hint</strong></summary>

Use `value_counts()`.

</details>

In [ ]:
# TODO: Calculate counts and percentages.

# TODO: Plot counts.

### Exercise 25: Reusable Numerical Profile

**Level:** Challenge  
**Learning objective:** Create a profiling function.

#### Task
Return count, missing percentage, mean, median, standard deviation, skewness, minimum, and maximum.

#### Expected result
```text
A pandas Series.
```

<details>
<summary><strong>Hint</strong></summary>

Accept the DataFrame and column name.

</details>

In [ ]:
def numerical_profile(
    data: pd.DataFrame,
    column: str,
) -> pd.Series:
    # TODO
    pass

### Exercise 26: Categorical Cardinality Audit

**Level:** Challenge  
**Learning objective:** Check uniqueness and dominant categories.

#### Task
Build a table containing unique count, missing count, top category, and top-category percentage.

#### Expected result
```text
One row per non-numerical column.
```

<details>
<summary><strong>Hint</strong></summary>

Use `value_counts(dropna=False)`.

</details>

In [ ]:
# TODO: Build categorical_audit.

# 7. Outlier Detection

An outlier may be:

- an entry error,
- an impossible value,
- a valid rare case,
- an influential business event.

## IQR Method

```text
IQR = Q3 - Q1
Lower = Q1 - 1.5 × IQR
Upper = Q3 + 1.5 × IQR
```

## Z-Score

```text
z = (x - mean) / standard deviation
```

The z-score method is sensitive to skewness and extreme observations.

Do not remove an outlier before deciding whether it is invalid, influential, or legitimately rare.

## Treatment Options

- correct from source,
- set impossible values to missing,
- keep and document,
- cap or winsorize,
- log-transform,
- use robust scaling,
- analyze results with and without extremes.

### Exercise 27: IQR Detection Function

**Level:** Applied  
**Learning objective:** Create reusable outlier detection.

#### Task
Return bounds, outlier count, and outlier rows.

#### Expected result
```text
A dictionary containing the analysis.
```

<details>
<summary><strong>Hint</strong></summary>

Drop missing values before quartile calculation.

</details>

In [ ]:
def detect_iqr_outliers(
    data: pd.DataFrame,
    column: str,
) -> dict:
    # TODO
    pass

### Exercise 28: Monthly-Spend Outliers

**Level:** Applied  
**Learning objective:** Apply IQR analysis.

#### Task
Print bounds, count, and sorted outlier values.

#### Expected result
```text
Dataset-dependent output.
```

<details>
<summary><strong>Hint</strong></summary>

Use the function from Exercise 27.

</details>

In [ ]:
# TODO: Analyze monthly_spend outliers.

### Exercise 29: Multi-Variable Outlier Summary

**Level:** Challenge  
**Learning objective:** Compare outlier prevalence.

#### Task
Create a summary for age, tenure, spend, calls, satisfaction, and purchases.

#### Expected result
```text
Include lower bound, upper bound, and count.
```

<details>
<summary><strong>Hint</strong></summary>

Loop through selected numerical variables.

</details>

In [ ]:
# TODO: Build outlier_summary.

### Exercise 30: Domain Invalidity

**Level:** Challenge  
**Learning objective:** Separate impossible values from statistical outliers.

#### Task
Count values violating domain rules for age, tenure, spend, satisfaction, support calls, and purchases.

#### Expected result
```text
One count per rule.
```

<details>
<summary><strong>Hint</strong></summary>

Define explicit expected ranges.

</details>

In [ ]:
# TODO: Create and evaluate domain rules.

### Exercise 31: Outlier Decision Register

**Level:** Challenge  
**Learning objective:** Document treatment choices.

#### Task
Create a table with variable, issue, evidence, decision, and justification.

#### Expected result
```text
At least six rows.
```

<details>
<summary><strong>Hint</strong></summary>

Use both IQR and domain analysis.

</details>

In [ ]:
# TODO: Build outlier_decisions.

# 8. Relationships and Correlations

## Numerical vs Numerical

- correlation,
- scatter plot,
- grouped statistics.

## Categorical vs Numerical

- group means and medians,
- separate boxplots,
- distribution comparison.

## Categorical vs Categorical

- crosstab,
- row percentages.

Correlation does not prove causation and may miss nonlinear relationships.

## Correlation Matrix

```python
correlation = df[numeric_columns].corr()
```

Values close to 1 or -1 indicate stronger linear relationships.

Self-correlation and duplicate variable pairs should be removed when listing strongest relationships.

### Exercise 32: Correlation Matrix

**Level:** Foundation  
**Learning objective:** Measure numerical relationships.

#### Task
Calculate the numerical correlation matrix.

#### Expected result
```text
A square matrix.
```

<details>
<summary><strong>Hint</strong></summary>

Use `.corr()`.

</details>

In [ ]:
# TODO: Create correlation_matrix.

### Exercise 33: Strongest Correlation Pairs

**Level:** Applied  
**Learning objective:** Extract useful relationships.

#### Task
List the five strongest absolute correlations excluding duplicate pairs and the diagonal.

#### Expected result
```text
Five variable pairs.
```

<details>
<summary><strong>Hint</strong></summary>

Use the upper triangle of the matrix.

</details>

In [ ]:
# TODO: Extract the strongest pairs.

### Exercise 34: Correlation Heatmap

**Level:** Applied  
**Learning objective:** Visualize numerical correlations.

#### Task
Create one labeled Matplotlib heatmap with a colorbar.

#### Expected result
```text
One heatmap.
```

<details>
<summary><strong>Hint</strong></summary>

Use `imshow()`.

</details>

In [ ]:
# TODO: Create the heatmap.

### Exercise 35: Tenure and Spend

**Level:** Applied  
**Learning objective:** Analyze a numerical relationship.

#### Task
Calculate correlation and create a scatter plot.

#### Expected result
```text
One correlation value and one scatter plot.
```

<details>
<summary><strong>Hint</strong></summary>

Drop rows missing either variable.

</details>

In [ ]:
# TODO: Calculate correlation.

# TODO: Create scatter plot.

### Exercise 36: Target Group Medians

**Level:** Applied  
**Learning objective:** Compare numerical variables across churn classes.

#### Task
Compare median tenure, spend, calls, satisfaction, and purchases.

#### Expected result
```text
A grouped median table.
```

<details>
<summary><strong>Hint</strong></summary>

Use `groupby('churn').median(numeric_only=True)`.

</details>

In [ ]:
# TODO: Create churn_median_comparison.

### Exercise 37: Contract Type vs Churn

**Level:** Applied  
**Learning objective:** Study two categorical variables.

#### Task
Create count and row-percentage crosstabs.

#### Expected result
```text
Two tables.
```

<details>
<summary><strong>Hint</strong></summary>

Use `pd.crosstab()`.

</details>

In [ ]:
# TODO: Build both crosstabs.

### Exercise 38: Premium Membership and Spend

**Level:** Challenge  
**Learning objective:** Compare a Boolean group with a numerical variable.

#### Task
Calculate grouped statistics and create two separate boxplot figures.

#### Expected result
```text
A grouped table and two figures.
```

<details>
<summary><strong>Hint</strong></summary>

Create one figure for each group.

</details>

In [ ]:
# TODO: Calculate grouped statistics.

# TODO: Plot premium customers in one figure.
# TODO: Plot non-premium customers in another figure.

### Exercise 39: Relationship Findings Register

**Level:** Challenge  
**Learning objective:** Interpret evidence.

#### Task
Document at least five relationships with question, evidence, interpretation, and caution.

#### Expected result
```text
At least five rows.
```

<details>
<summary><strong>Hint</strong></summary>

Use correlations, group statistics, and crosstabs.

</details>

In [ ]:
# TODO: Build relationship_findings.

# 9. Class-Balance Analysis

For classification, inspect the target distribution.

```python
counts = df["churn"].value_counts()
percentages = df["churn"].value_counts(normalize=True) * 100
```

An imbalanced target may make accuracy misleading.

Consider:

- stratified train/test split,
- precision,
- recall,
- F1-score,
- confusion matrix,
- ROC-AUC,
- PR-AUC,
- class weights,
- resampling when justified.

### Exercise 40: Target Distribution

**Level:** Foundation  
**Learning objective:** Measure class balance.

#### Task
Print churn counts and percentages.

#### Expected result
```text
Approximate counts: {'No': 294, 'Yes': 34}
```

<details>
<summary><strong>Hint</strong></summary>

Use `value_counts()`.

</details>

In [ ]:
# TODO: Calculate and print counts and percentages.

### Exercise 41: Target Bar Chart

**Level:** Foundation  
**Learning objective:** Visualize class balance.

#### Task
Create one labeled bar chart.

#### Expected result
```text
One chart.
```

<details>
<summary><strong>Hint</strong></summary>

Plot the count Series.

</details>

In [ ]:
# TODO: Plot churn counts.

### Exercise 42: Balance by Contract Type

**Level:** Applied  
**Learning objective:** Inspect target balance within subgroups.

#### Task
Calculate churn percentages within each contract type.

#### Expected result
```text
A row-normalized crosstab.
```

<details>
<summary><strong>Hint</strong></summary>

Use `normalize='index'`.

</details>

In [ ]:
# TODO: Calculate the crosstab.

### Exercise 43: Imbalance Recommendation

**Level:** Challenge  
**Learning objective:** Connect EDA to modeling decisions.

#### Task
Write a recommendation covering split strategy, metrics, and whether resampling should be considered.

#### Expected result
```text
A printed recommendation.
```

<details>
<summary><strong>Hint</strong></summary>

Base the recommendation on observed percentages.

</details>

In [ ]:
recommendation = '''
TODO
'''

print(recommendation)

TODO

# 10. Domain-Validity and Logical Checks

Statistics do not replace domain knowledge.

Check:

- plausible ages,
- non-negative spending,
- score ranges,
- allowed categories,
- identifier format,
- date consistency,
- logical relationships between fields.

### Exercise 44: Allowed Categories

**Level:** Applied  
**Learning objective:** Validate categorical domains.

#### Task
Check gender, contract type, payment method, and churn against allowed sets.

#### Expected result
```text
One invalid count per column.
```

<details>
<summary><strong>Hint</strong></summary>

Use `.isin()` and ignore missing values appropriately.

</details>

In [ ]:
# TODO: Define allowed categories.

# TODO: Print invalid counts.

### Exercise 45: Customer-ID Validation

**Level:** Applied  
**Learning objective:** Check completeness, uniqueness, and format.

#### Task
Count null IDs, duplicate IDs, and malformed IDs.

#### Expected result
```text
Three validation counts.
```

<details>
<summary><strong>Hint</strong></summary>

A valid ID starts with `CUST-` and has nine characters.

</details>

In [ ]:
# TODO: Validate customer_id.

### Exercise 46: Date-Tenure Consistency

**Level:** Challenge  
**Learning objective:** Compare related variables.

#### Task
Estimate account age from signup date relative to 2026-07-01 and flag differences greater than six months.

#### Expected result
```text
A table of suspicious rows.
```

<details>
<summary><strong>Hint</strong></summary>

Use date differences divided by approximately 30.44 days.

</details>

In [ ]:
# TODO: Calculate estimated tenure.

# TODO: Flag inconsistent rows.

### Exercise 47: Data-Quality Scorecard

**Level:** Challenge  
**Learning objective:** Summarize quality dimensions.

#### Task
Create a scorecard for completeness, uniqueness, validity, consistency, and notes.

#### Expected result
```text
One row per dimension.
```

<details>
<summary><strong>Hint</strong></summary>

Use percentages where possible.

</details>

In [ ]:
# TODO: Build data_quality_scorecard.

# 11. Transformations Before Modeling

EDA should identify required preprocessing.

## Missing Values

- median,
- mode,
- explicit `Unknown`,
- missing indicator.

## Categorical Features

- one-hot encoding,
- ordinal encoding only when order is real,
- rare-category consolidation.

## Numerical Features

- standardization,
- robust scaling,
- log transformation,
- clipping after investigation.

## Dates

- year,
- month,
- weekday,
- account age.

## Leakage Warning

Transformations and imputations should be fitted on training data only.

### Exercise 48: Create a Modeling Copy

**Level:** Foundation  
**Learning objective:** Preserve raw data.

#### Task
Create `model_df` from the deduplicated copy.

#### Expected result
```text
The raw DataFrame remains unchanged.
```

<details>
<summary><strong>Hint</strong></summary>

Use `.copy()`.

</details>

In [ ]:
# TODO: Create model_df.

### Exercise 49: Convert Invalid Values to Missing

**Level:** Applied  
**Learning objective:** Prepare invalid observations for treatment.

#### Task
Set domain-invalid age, tenure, spend, satisfaction, calls, and purchases to NaN.

#### Expected result
```text
Invalid values become missing.
```

<details>
<summary><strong>Hint</strong></summary>

Use Boolean masks with `.loc`.

</details>

In [ ]:
# TODO: Replace invalid values with np.nan.

### Exercise 50: Impute Selected Variables

**Level:** Applied  
**Learning objective:** Apply simple justified imputations.

#### Task
Use median for numerical variables and mode or `Unknown` for categorical variables.

#### Expected result
```text
Selected columns should have no missing values.
```

<details>
<summary><strong>Hint</strong></summary>

Document each rule in code comments.

</details>

In [ ]:
# TODO: Impute numerical variables.

# TODO: Impute categorical variables.

# TODO: Print remaining missing counts.

### Exercise 51: Engineer Date Features

**Level:** Applied  
**Learning objective:** Extract modeling features from dates.

#### Task
Create signup year, signup month, and account age in months.

#### Expected result
```text
Three new columns.
```

<details>
<summary><strong>Hint</strong></summary>

Use the reference date 2026-07-01.

</details>

In [ ]:
# TODO: Create date features.

### Exercise 52: Encode the Target

**Level:** Foundation  
**Learning objective:** Convert a binary label to numbers.

#### Task
Create `churn_flag` where No=0 and Yes=1.

#### Expected result
```text
Only 0 and 1.
```

<details>
<summary><strong>Hint</strong></summary>

Use `.map()`.

</details>

In [ ]:
# TODO: Create churn_flag.

# TODO: Print value counts.

### Exercise 53: One-Hot Encoding

**Level:** Applied  
**Learning objective:** Prepare nominal categorical variables.

#### Task
Create dummy columns for contract type and payment method.

#### Expected result
```text
A new encoded DataFrame.
```

<details>
<summary><strong>Hint</strong></summary>

Use `pd.get_dummies()`.

</details>

In [ ]:
# TODO: Create encoded_df.

### Exercise 54: Log Transformation

**Level:** Challenge  
**Learning objective:** Reduce strong right skew.

#### Task
Create `monthly_spend_log` and compare skewness before and after.

#### Expected result
```text
Two skewness values.
```

<details>
<summary><strong>Hint</strong></summary>

Use `np.log1p()` after invalid values and missingness are handled.

</details>

In [ ]:
# TODO: Transform monthly_spend.

# TODO: Compare skewness.

### Exercise 55: Transformation Plan

**Level:** Challenge  
**Learning objective:** Document preprocessing decisions.

#### Task
Create a plan with variable, issue, transformation, reason, and leakage precaution.

#### Expected result
```text
At least eight rows.
```

<details>
<summary><strong>Hint</strong></summary>

Include date, categorical, numerical, target, and ID variables.

</details>

In [ ]:
# TODO: Build transformation_plan.

# 12. Documenting EDA Findings

A useful finding separates:

1. observation,
2. evidence,
3. interpretation,
4. impact,
5. recommended action.

## Finding Template

| Field | Meaning |
|---|---|
| area | Missingness, outlier, relationship, balance |
| finding | What was observed |
| evidence | Number, percentage, statistic, or chart |
| impact | Why it matters |
| recommended_action | Next step |
| priority | High, medium, low |

A final report should explicitly answer whether the data is ready for analysis and modeling.

### Exercise 56: Findings Register

**Level:** Challenge  
**Learning objective:** Create an auditable EDA record.

#### Task
Document at least twelve findings covering all major EDA areas.

#### Expected result
```text
At least twelve rows.
```

<details>
<summary><strong>Hint</strong></summary>

Use evidence from earlier sections.

</details>

In [ ]:
# TODO: Build findings_register.

### Exercise 57: Executive EDA Summary

**Level:** Challenge  
**Learning objective:** Communicate technical findings clearly.

#### Task
Write 250–400 words covering readiness, issues, relationships, balance, and required transformations.

#### Expected result
```text
A structured executive summary.
```

<details>
<summary><strong>Hint</strong></summary>

Use evidence, not general statements.

</details>

In [ ]:
eda_executive_summary = '''
TODO
'''

print(eda_executive_summary)

TODO

# 13. Final Guided EDA Project

Complete a full analysis on a fresh copy of the dataset.

## Required Deliverables

### Data Understanding
- purpose,
- unit of analysis,
- target,
- data dictionary.

### Initial Inspection
- samples,
- shape,
- columns,
- data types.

### Quality
- missing values,
- duplicates,
- identifier uniqueness,
- invalid categories,
- unreasonable numerical values.

### Descriptive Analysis
- numerical and categorical summaries,
- distributions,
- class balance.

### Outliers
- IQR results,
- domain-invalid values,
- decisions.

### Relationships
- correlation matrix,
- at least three numerical relationships,
- at least three grouped or categorical comparisons.

### Modeling Preparation
- missing-value strategy,
- encoding,
- scaling/transformation,
- feature engineering,
- leakage risks.

### Final Reporting
- findings register,
- executive summary,
- readiness decision.

In [ ]:
# FINAL PROJECT WORKSPACE

# 1. Load a fresh copy.
# 2. Inspect structure and types.
# 3. Analyze missingness and duplicates.
# 4. Validate numerical and categorical values.
# 5. Analyze distributions.
# 6. Detect and interpret outliers.
# 7. Analyze relationships.
# 8. Inspect target balance.
# 9. Create a transformation plan.
# 10. Write findings and final recommendation.

## Final Readiness Decision Template

```text
Dataset readiness: Ready / Conditionally ready / Not ready

Critical issues:

Required cleaning:

Important variables:

Strongest relationships:

Class-balance conclusion:

Required transformations:

Potential leakage risks:

Final recommendation:
```

In [ ]:
final_readiness_decision = '''
Dataset readiness:

Critical issues:

Required cleaning:

Important variables:

Strongest relationships:

Class-balance conclusion:

Required transformations:

Potential leakage risks:

Final recommendation:
'''

print(final_readiness_decision)

Dataset readiness:

Critical issues:

Required cleaning:

Important variables:

Strongest relationships:

Class-balance conclusion:

Required transformations:

Potential leakage risks:

Final recommendation:

# Assessment Rubric — 100 Points

| Area | Points |
|---|---:|
| Loading and inspection | 8 |
| Missing values | 10 |
| Duplicates and identifiers | 8 |
| Descriptive statistics | 10 |
| Distribution analysis | 10 |
| Outliers and validity | 12 |
| Relationships and correlations | 14 |
| Target balance | 8 |
| Transformation plan | 10 |
| Documentation | 10 |
| **Total** | **100** |

# Submission Checklist

- [ ] Dataset loaded successfully.
- [ ] Samples displayed.
- [ ] Shape, columns, and types documented.
- [ ] Dates converted.
- [ ] Missing values quantified and interpreted.
- [ ] Duplicate rows and IDs checked.
- [ ] Descriptive statistics reviewed.
- [ ] Numerical and categorical distributions analyzed.
- [ ] Statistical outliers detected.
- [ ] Domain-invalid values identified.
- [ ] Correlations and group relationships studied.
- [ ] Target balance documented.
- [ ] Transformation plan completed.
- [ ] At least twelve findings documented.
- [ ] Executive summary completed.
- [ ] Final readiness decision completed.